# GitHub repository settings
# This file is used with the GitHub Settings Probot app to manage repository settings as code
# See https://github.com/apps/settings for installation

repository:
  # Basic repository settings
  name: balatro-rs
  description: "A game engine and move generator for Balatro, written in Rust with Python bindings"
  topics:
    - rust
    - game-engine
    - reinforcement-learning
    - python-bindings
    - balatro

  # Make repository public
  private: false

  # Enable features
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: true

  # Set default branch
  default_branch: main

  # Merge button settings
  # Only allow squash merging to keep a clean commit history
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false

  # Use PR title for squash merge commits
  squash_merge_commit_title: "PR_TITLE"
  squash_merge_commit_message: "PR_BODY"

  # Delete branches after merge
  delete_branch_on_merge: true

  # Require branches to be up to date before merging
  allow_update_branch: true

# Branch protection rules
branches:
  - name: main
    protection:
      # Require PR reviews
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: false
        dismissal_restrictions: {}

      # Require status checks
      required_status_checks:
        strict: true
        contexts:
          - "Test Suite (ubuntu-latest)"
          - "Test Suite (windows-latest)"
          - "Test Suite (macos-latest)"
          - "Rustfmt"
          - "Clippy"
          - "Code Coverage"
          - "Python Bindings Test"

      # Enforce restrictions
      enforce_admins: false
      required_linear_history: true
      restrictions: null

      # Allow force pushes and deletions by admins only
      allow_force_pushes: false
      allow_deletions: false

      # Require conversation resolution
      required_conversation_resolution: true

# Labels for issues and PRs
labels:
  - name: bug
    color: d73a4a
    description: "Something isn't working"

  - name: enhancement
    color: a2eeef
    description: "New feature or request"

  - name: documentation
    color: 0075ca
    description: "Improvements or additions to documentation"

  - name: good first issue
    color: 7057ff
    description: "Good for newcomers"

  - name: help wanted
    color: 008672
    description: "Extra attention is needed"

  - name: question
    color: d876e3
    description: "Further information is requested"

  - name: wontfix
    color: ffffff
    description: "This will not be worked on"

  - name: duplicate
    color: cfd3d7
    description: "This issue or pull request already exists"

  - name: invalid
    color: e4e669
    description: "This doesn't seem right"

  - name: performance
    color: f9d0c4
    description: "Performance improvements"

  - name: refactor
    color: ef67c4
    description: "Code refactoring"

  - name: testing
    color: bfd4f2
    description: "Testing improvements"

  - name: ci/cd
    color: fef2c0
    description: "Continuous Integration/Deployment"

  - name: dependencies
    color: 0366d6
    description: "Pull requests that update a dependency file"

  - name: rust
    color: ce422b
    description: "Rust code changes"

  - name: python
    color: 3572a5
    description: "Python bindings changes"
