name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    container:
      image: rust:slim
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y pkg-config libssl-dev python3 python3-dev
      
      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-
      
      - name: Cache cargo build
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-build-target-
      
      - name: Run tests
        run: cargo test --all --verbose

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    container:
      image: rust:slim
    steps:
      - uses: actions/checkout@v4
      
      - name: Install rustfmt
        run: rustup component add rustfmt
      
      - name: Check formatting
        run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    container:
      image: rust:slim
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y pkg-config libssl-dev python3 python3-dev
      
      - name: Install clippy
        run: rustup component add clippy
      
      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-
      
      - name: Cache cargo build
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-clippy-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-build-target-clippy-
      
      - name: Run clippy
        run: cargo clippy --all -- -D warnings

  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Python and dependencies
        run: |
          apt-get update
          apt-get install -y python3 python3-dev python3-venv python3-pip pkg-config libssl-dev
          
      - name: Setup Python virtual environment
        run: |
          python3 -m venv /opt/venv
          echo "/opt/venv/bin" >> $GITHUB_PATH
          
      - name: Cache cargo tools
        uses: actions/cache@v3
        id: cargo-tools-cache
        with:
          path: |
            ~/.cargo/bin/cargo-tarpaulin
          key: ${{ runner.os }}-cargo-tools-tarpaulin-0.27.0
      
      - name: Install coverage tools
        run: |
          if ! command -v cargo-tarpaulin &> /dev/null; then
            cargo install cargo-tarpaulin --version 0.27.0
          fi
          # Use the virtual environment's pip
          /opt/venv/bin/pip install --upgrade pip
          /opt/venv/bin/pip install maturin pytest pytest-cov
      
      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-
      
      - name: Generate Rust code coverage
        run: |
          # Run coverage on core library with Python feature
          cargo tarpaulin --verbose --features python,serde,colored --timeout 120 --out xml --output-dir coverage -p balatro-rs
      
      - name: Upload Rust coverage to codecov.io
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/cobertura.xml
          flags: rust
          fail_ci_if_error: false
      
      - name: Build Python extension for coverage
        run: |
          cd pylatro
          /opt/venv/bin/maturin develop
      
      - name: Run Python tests with coverage
        run: |
          cd pylatro
          /opt/venv/bin/python -m pytest test/test_pylatro.py -v --cov=pylatro --cov-report=xml
      
      - name: Upload Python coverage to codecov.io
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./pylatro/coverage.xml
          flags: python
          fail_ci_if_error: false

  # Ensure all workspace members build successfully
  build-all:
    name: Build All Workspace Members
    runs-on: ubuntu-latest
    container:
      image: rust:slim
    strategy:
      matrix:
        member: [balatro-rs, balatro-cli, pylatro]
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y pkg-config libssl-dev python3 python3-dev
      
      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-
      
      - name: Cache cargo build
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-${{ matrix.member }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-build-${{ matrix.member }}-
      
      - name: Build workspace member
        run: cargo build -p ${{ matrix.member }} --verbose

  # Run benchmarks to ensure they compile (but don't fail on performance)
  bench-check:
    name: Benchmark Compilation Check
    runs-on: ubuntu-latest
    container:
      image: rust:slim
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y pkg-config libssl-dev python3 python3-dev
      
      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-
      
      - name: Cache cargo build
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-bench-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-build-bench-
      
      - name: Check benchmarks compile
        run: cargo bench --no-run -p balatro-rs